config:
  install_tree: /appl/spack/run
  install_path_scheme: ${COMPILERNAME}-${COMPILERVER}/${PACKAGE}-${VERSION}-${HASH:6}
  build_stage::
    - /appl/spack/run/stage
  module_roots:
    lmod: /appl/spack/run/modulefiles
  source_cache: /appl/spack/run/sources
