config:
  build_jobs:: 20
  install_tree: /appl/test/lumi-test/install-tree
  install_path_scheme: ${COMPILERNAME}-${COMPILERVER}/${PACKAGE}-${VERSION}-${HASH:6}
  build_stage::
    - /local_scratch/build/spack-stage-lumi-test
  module_roots:
    lmod: /appl/test/lumi-test/modulefiles
  source_cache: /appl/spack/sources
