config:
  build_jobs:: 20
  install_tree: /appl/spack/v014/install-tree
  install_path_scheme: ${COMPILERNAME}-${COMPILERVER}/${PACKAGE}-${VERSION}-${HASH:6}
  build_stage::
    - /local_scratch/spack-stage
  module_roots:
    lmod: /appl/spack/v014/modulefiles
  source_cache: /appl/spack/v014/spack/sources
