config:
  install_tree: /appl/spack
  install_path_scheme: ${COMPILERNAME}-${COMPILERVER}/${PACKAGE}-${VERSION}-${HASH:6}
  build_stage::
    - /appl/spack/stage
  module_roots:
    lmod: /appl/spack/modulefiles
  source_cache: /appl/spack/sources
